please

diff --git a/.github/workflows/scrape.yml b/.github/workflows/scrape.yml
--- a/.github/workflows/scrape.yml
+++ b/.github/workflows/scrape.yml
@@ -50,7 +50,7 @@ jobs:
         python amiami-sales.py
         echo "Scraper run complete."
         ls -lh AmiAmi_sales.csv || echo "CSV not found"
-        ls -lh AmiAmi_sales.md || echo "md not found"
+        ls -lh README.md || echo "md not found"
         ls -lh AmiAmi_sales.xlsx || echo "md not found"
         git status
 
@@ -58,7 +58,7 @@ jobs:
       run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
-        git add AmiAmi_sales.csv AmiAmi_sales.md
+        git add AmiAmi_sales.csv README.md
         git add AmiAmi_sales.xlsx
         git commit -m "Auto-update CSV/MD" || echo "No changes to commit"
         git pull --rebase origin main || echo "No rebase needed"
